# server.yml
server.httpPort: 9080
server.enableHttp: true
server.enableHttps: true
server.enableHttp2: true
server.serviceId: com.networknt.client-gateway-1.0.0
server.environment: dev

# router.yml
router.maxRequestTime: 30000

# rule-loader.yml
rule-Loader.ruleSource: config-folder
rule-loader.endpointRules: {"/v1/notifications@get":{"response-transform":[{"ruleId":"petstore-notifications-transformer"}]},"/pets@get":{"request-transform":[{"ruleId":"petstore-request-path"}]},"/v1/flowers@post":{"request-transform":[{"ruleId":"petstore-flower-request"}],"response-transform":[{"ruleId":"petstore-flower-response"}]},"/devext/CANX/AntcMultiService@post":{"request-transform":[{"ruleId":"soap-security-request"}]}}

# response-transformer.yml
response-transformer.appliedPathPrefixes: ["/v1/notifications","/v1/flowers"]

# request-transformer.yml
request-transformer.appliedPathPrefixes: ["/pets","/v1/flowers","/devext/CANX/AntcMultiService"]

# pathPrefixService.yml
pathPrefixService.mapping:
  # /gateway/Migration/1.0.0: Migration
  /v1/pets: com.networknt.petstore-1.0.0
  /pets: com.networknt.petstore-1.0.0
  /v1/notifications: com.networknt.petstore-1.0.0
  /v1/flowers: com.networknt.petstore-1.0.0

# service.yml
service.singletons:
  - com.networknt.server.StartupHookProvider:
      - com.networknt.rule.RuleLoaderStartupHook
  - com.networknt.registry.URL:
      - com.networknt.registry.URLImpl:
          parameters:
            # com.networknt.portal.hybrid.query-1.0.0: https://hybrid-query1:8440,https://hybrid-query2:8441,https://hybrid-query3:8442
            # com.networknt.portal.hybrid.command-1.0.0: https://hybrid-command:8439
            # com.networknt.oauth-key-1.0.0: https://oauth-key:6886
            # com.networknt.oauth-token-1.0.0: https://oauth-token:6882
            # com.networknt.oauth-code-1.0.0: https://oauth-code:6881
            # com.networknt.reference-1.0.0: https://reference:2498
            # com.networknt.config-server-1.0.0: https://localhost:8435
            # com.networknt.controller-1.0.0: https://controller-node1:8438,https://controller-node2:8437,https://controller-node3:8436
            # com.networknt.scheduler-1.0.0: https://scheduler-node1:8401,https://scheduler-node2:8402,https://scheduler-node3:8403
            # Migration: https://lightgateway-dev.networknt.com:8443
            com.networknt.petstore-1.0.0: https://localhost:9443
  - com.networknt.registry.Registry:
      - com.networknt.registry.support.DirectRegistry
  - com.networknt.balance.LoadBalance:
      - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
      - com.networknt.cluster.LightCluster
  - com.networknt.utility.Decryptor:
      - com.networknt.decrypt.AESDecryptor
  - com.networknt.handler.ResponseInterceptor:
      - com.networknt.body.ResponseBodyInterceptor
      - com.networknt.restrans.ResponseTransformerInterceptor
  - com.networknt.handler.RequestInterceptor:
      - com.networknt.body.RequestBodyInterceptor
      - com.networknt.reqtrans.RequestTransformerInterceptor

# handler.yml
handler.basePath: /
handler.handlers:
  # Light-framework cross-cutting concerns implemented in the microservice
  - com.networknt.exception.ExceptionHandler@exception
  - com.networknt.metrics.MetricsHandler@metrics
  - com.networknt.traceability.TraceabilityHandler@traceability
  - com.networknt.correlation.CorrelationHandler@correlation
  # Cors handler to handler post/put pre-flight. It is not used in the sidecar but only in the router.
  - com.networknt.cors.CorsHttpHandler@cors
  - com.networknt.openapi.OpenApiHandler@specification
  - com.networknt.openapi.JwtVerifyHandler@security
  - com.networknt.body.BodyHandler@body
  - com.networknt.audit.AuditHandler@audit
  - com.networknt.sanitizer.SanitizerHandler@sanitizer
  - com.networknt.openapi.ValidatorHandler@validator
  # Header middleware to manipulate request and/or response headers before or after downstream server
  - com.networknt.header.HeaderHandler@header
  # Rate limit middleware to prevent DDoS attacks externally or throttle requests internally
  - com.networknt.limit.LimitHandler@limit
  # IP whitelist handler to allow only one or several IPs to connect to the gateway.
  #  - com.networknt.whitelist.WhitelistHandler@whitelist
  # Direct requests to named services based on the request path
  # - com.networknt.router.middleware.GatewayServiceDictHandler@path
  - com.networknt.router.middleware.PathPrefixServiceHandler@prefix
  - com.networknt.router.middleware.GatewaySAMLTokenHandler@saml
  - com.networknt.router.GatewayRouterHandler@router
  - com.networknt.proxy.LightProxyHandler@proxy
  - com.networknt.proxy.ProxyServerInfoHandler@proxyServerInfo
  # - com.networknt.resource.VirtualHostHandler@virtual
  # Customer business domain specific cross-cutting concerns handlers
  # - com.example.validator.CustomizedValidator@custvalidator
  # Framework endpoint handlers
  # Control Pane middleware handlers and API handler
  - com.networknt.chaos.KillappAssaultHandler@killapp
  - com.networknt.chaos.LatencyAssaultHandler@latency
  - com.networknt.chaos.MemoryAssaultHandler@memory
  - com.networknt.chaos.ExceptionAssaultHandler@exchaos
  - com.networknt.chaos.ChaosMonkeyGetHandler@chaosget
  - com.networknt.chaos.ChaosMonkeyPostHandler@chaospost
  - com.networknt.health.HealthGetHandler@health
  - com.networknt.info.ServerInfoGetHandler@info
  - com.networknt.logging.handler.LoggerGetHandler@getLogger
  - com.networknt.logging.handler.LoggerPostHandler@postLogger
  - com.networknt.logging.handler.LoggerGetLogContentsHandler@getLogContents
  - com.networknt.config.reload.handler.ModuleRegistryGetHandler@modules
  - com.networknt.config.reload.handler.ConfigReloadHandler@configReload
  - com.networknt.specification.SpecDisplayHandler@spec
  - com.networknt.specification.SpecSwaggerUIHandler@swaggerui
  - com.networknt.specification.FaviconHandler@favicon
  - com.networknt.handler.ResponseInterceptorInjectionHandler@responseInterceptor
  - com.networknt.handler.RequestInterceptorInjectionHandler@requestInterceptor
  - com.networknt.proxy.ExternalServiceHandler@external
  - com.networknt.proxy.conquest.ConquestHandler@conquest
  - com.networknt.server.handler.ServerShutdownHandler@shutdown

handler.chains.default:
  - exception
  # - metrics
  # - limit
  - traceability
  - correlation
  # - cors
  # - stateless
  - requestInterceptor
  - responseInterceptor
  - header
  - audit
  - conquest
  - external
  #- path
  #- specification
  #- security
  #- body
  #- sanitizer
  #- validator
  - prefix
  - router

# audit.yml
audit.auditOnError: false

# body.yml
body.cacheRequestBody: true

# external-service.yml
externalService.enabled: true
externalService.enableHttp2: true
externalService.pathHostMappings:
  - /devext/CANX/AntcMultiService https://wwwdev.cannex.com
  - /direct/services/request/init https://www.chasepaymentechhostedpay-var.com
  - /api/compliance/state/level/v1/levels:filterLeve https://sunlife.blackrock.com

# client.yml
client.verifyHostname: false

# header.yml
header.enabled: true
header.request.update:
  VND.com.blackrock.Request-ID: 3e161420-1b0a-11ec-b966-475f9c199ac4
  VND.com.blackrock.API-Key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIqIiwiYXBwSWQiOiJ0ZXN0Y2xpZW50bGcxIiwic2VydmljZUdyb3VwcyI6W10sImRldGFpbHMiOiJbXSIsImlkIjoiNzM4OWQ0YzctYjVjMi00ZDlmLWEzYzYtNWYzMDJiODQ2MTllIiwiZXhwIjo3OTgzNzkyMDAwfQ.f6SLQ06uczp-10UTM2R-8wBoB-du4vVGHLSnguZL_88
  x-traceability-id: test-traceability
  x-correlation-id: test-correlation

# conquest.yam
conquest.enabled: true
conquest.certFilename: conquestuat.jks
conquest.certPassword: Password1!!!
conquest.pathPrefixAuths: [{"pathPrefix":"/conquest","authIssuer":"Sunlife","authSubject":"conquest-public-uat-sunlife-jwt-integration","authAudience":"app://d5b1cb55-3835-52fc-9ef3-e38d58856394","tokenTtl":180,"tokenUrl":"https://sunlife-auth.uat.conquest-public.conquestplanning.com/login/oauth2/realms/root/realms/con/realms/uat/access_token","serviceHost":"https://conquestplanning.com"}]
