# service.yml
service.singletons:
  - com.networknt.utility.Decryptor:
      - com.networknt.decrypt.AESDecryptor
  - com.networknt.balance.LoadBalance:
      - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
      - com.networknt.cluster.LightCluster

# handler.yml
handler.basePath: /v1

# server.yml
server.serviceId: com.networknt.gateway-1.0.0

# proxy.yml
proxy.host: https://localhost:9443

# router.yml
router.hostWhitelist:
  - 192.168.0.*
  - localhost

