apiVersion: v1
kind: ConfigMap
metadata:
  name: ${name:light-gateway}-config
  namespace: ${namespace:light-gateway}
  labels:
    app.kubernetes.io/name: ${name:light-gateway}
    app.kubernetes.io/component: micro-gateway
data:
  startup.yml: |
    configLoaderClass: com.networknt.server.DefaultConfigLoader
    host: ${startup.host:dev.lightapi.net}
    serviceId: ${startup.serviceId:com.networknt.ai.gateway-1.0.0}
    envTag: ${startup.envTag:dev}
    acceptHeader: application/yaml
    timeout: ${startup.timeout:3000}
  