apiVersion: v1
kind: ConfigMap
metadata:
  name: ${name:light-gateway}-config
  namespace: ${namespace:light-gateway}
  labels:
    app.kubernetes.io/name: ${name:light-gateway}
    app.kubernetes.io/component: micro-gateway
data:
  startup.yml: |
    configLoaderClass: com.networknt.server.DefaultConfigLoader
    host: ${startup.host:dev.lightapi.net}
    serviceId: ${startup.serviceId:com.networknt.ai.gateway-1.0.0}
    envTag: ${startup.envTag:dev}
    acceptHeader: application/yaml
    timeout: ${startup.timeout:3000}
  logback.xml: |
    <configuration>
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] %logger{36} - %msg%n</pattern>
        </encoder>
      </appender>
      <root level="${log.level:INFO}">
        <appender-ref ref="STDOUT"/>
      </root>
    </configuration>
