apiVersion: v1
kind: Secret
metadata:
  name: ${name:light-gateway}-bootstrap
  namespace: ${namespace:light-gateway}
  labels:
    app.kubernetes.io/name: ${name:light-gateway}
    app.kubernetes.io/component: micro-gateway
type: Opaque
stringData:
  light-4j-config-password: ${light4jConfigPassword:DEV}
  config-server-client-truststore-password: ${configServerTruststorePassword:password}
  light-portal-authorization: ${lightPortalAuthorization:}
data:
  bootstrap.truststore: ${bootstrapTruststoreBase64}
