# We don't need this image as we can pass the environment variable to any container with JAVA_TOOL_OPTIONS
FROM amazoncorretto:11.0.21
ADD /target/light-gateway.jar server.jar
CMD ["/bin/sh","-c","exec java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005 -Dlight-4j-config-dir=/config -Dlogback.configurationFile=/config/logback.xml -jar /server.jar"]
