# server.yml
server.httpsPort: 7443
server.serviceId: com.networknt.server-gateway-1.0.0

# router.yml
router.maxRequestTime: 30000

# pathPrefixService.yml
pathPrefixService.mapping:
  /gateway/Migration/1.0.0: Migration

# service.yml
service.singletons:
  - com.networknt.registry.URL:
      - com.networknt.registry.URLImpl:
          protocol: https
          host: localhost
          port: 7080
          path: direct
          parameters:
            # com.networknt.portal.hybrid.query-1.0.0: https://hybrid-query1:8440,https://hybrid-query2:8441,https://hybrid-query3:8442
            # com.networknt.portal.hybrid.command-1.0.0: https://hybrid-command:8439
            # com.networknt.oauth-key-1.0.0: https://oauth-key:6886
            # com.networknt.oauth-token-1.0.0: https://oauth-token:6882
            # com.networknt.oauth-code-1.0.0: https://oauth-code:6881
            # com.networknt.reference-1.0.0: https://reference:2498
            # com.networknt.config-server-1.0.0: https://localhost:8435
            # com.networknt.controller-1.0.0: https://controller-node1:8438,https://controller-node2:8437,https://controller-node3:8436
            # com.networknt.scheduler-1.0.0: https://scheduler-node1:8401,https://scheduler-node2:8402,https://scheduler-node3:8403
            Migration: https://lightgateway-dev.networknt.com:8443
  - com.networknt.registry.Registry:
      - com.networknt.registry.support.DirectRegistry
  - com.networknt.balance.LoadBalance:
      - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
      - com.networknt.cluster.LightCluster
  - com.networknt.cache.CacheManager:
      - com.networknt.cache.CaffeineCacheManager

#client.yml
client.verifyHostname: false
#client.tokenCcClientId: f7d42348-c647-4efb-a52d-4c5787421e73
#client.tokenRtClientId: f7d42348-c647-4efb-a52d-4c5787421e73
#client.tokenKeyClientId: f7d42348-c647-4efb-a52d-4c5787421e73
#client.signClientId: f7d42348-c647-4efb-a52d-4c5787421e73
#client.signKeyClientId: f7d42348-c647-4efb-a52d-4c5787421e73
#client.derefClientId: f7d42348-c647-4efb-a52d-4c5787421e73
#client.injectOpenTracing: true
#client.tokenServiceId: com.networknt.oauth-token-1.0.0
#client.tokenKeyServiceId: com.networknt.oauth-key-1.0.0
#client.signServiceId: com.networknt.oauth-token-1.0.0
#client.signKeyServiceId: com.networknt.oauth-key-1.0.0
#client.derefServiceId: com.networknt.oauth-token-1.0.0


# whitelist.yml
whitelist.enabled: false
whitelist.paths:
  # For a particular endpoint(path@method), there are three IPs can access
  '/health/com.networknt.petstore-1.0.0@get':
    # IPv4 Exact
    - '127.0.0.1'
    # IPv4 Wildcard
    - '10.10.*.*'
    # IPv4 Slash
    - '127.0.0.48/30'

  # For a path, the following IP can access regardless the method
  '/prometheus@get':
    # IPv6 Exact
    - 'FE45:00:00:000:0:AAA:FFFF:0045'
    # IPv6 Prefix
    - 'FE45:00:00:000:0:AAA:FFFF:*'
    # IPv6 Slash
    - 'FE45:00:00:000:0:AAA:FFFF:01F4/127'

  # For a particular endpoint(path@method), there are three IPs can access
  '/data@get':
    # IPv4 Exact
    - '127.0.0.2'
    # IPv4 Wildcard
    - '10.10.*.*'
    # IPv4 Slash
    - '127.0.0.48/30'

# handler.yml
handler.enabled: true
handler.basePath: /
handler.handlers:
  # Light-framework cross-cutting concerns implemented in the microservice
  - com.networknt.exception.ExceptionHandler@exception
  - com.networknt.metrics.MetricsHandler@metrics
  - com.networknt.traceability.TraceabilityHandler@traceability
  - com.networknt.correlation.CorrelationHandler@correlation
  # Cors handler to handler post/put pre-flight. It is not used in the sidecar but only in the router.
  - com.networknt.cors.CorsHttpHandler@cors
  - com.networknt.openapi.OpenApiHandler@specification
  - com.networknt.openapi.JwtVerifyHandler@security
  - com.networknt.body.ProxyBodyHandler@body
  - com.networknt.audit.AuditHandler@audit
  - com.networknt.sanitizer.SanitizerHandler@sanitizer
  - com.networknt.openapi.ValidatorHandler@validator
  # Header middleware to manipulate request and/or response headers before or after downstream server
  - com.networknt.header.HeaderHandler@header
  # Rate limit middleware to prevent DDoS attacks externally or throttle requests internally
  - com.networknt.limit.LimitHandler@limit
  # IP whitelist handler to allow only one or several IPs to connect to the gateway.
  #  - com.networknt.whitelist.WhitelistHandler@whitelist
  # Direct requests to named services based on the request path
  # - com.networknt.router.middleware.GatewayServiceDictHandler@path
  - com.networknt.router.middleware.PathPrefixServiceHandler@prefix
  # - com.networknt.router.middleware.GatewaySAMLTokenHandler@saml
  - com.networknt.router.RouterHandler@router
  - com.networknt.proxy.LightProxyHandler@proxy
  - com.networknt.proxy.ProxyServerInfoHandler@proxyServerInfo
  # - com.networknt.resource.VirtualHostHandler@virtual
  # Customer business domain specific cross-cutting concerns handlers
  # - com.example.validator.CustomizedValidator@custvalidator
  # Framework endpoint handlers
  # Control Pane middleware handlers and API handler
  - com.networknt.chaos.KillappAssaultHandler@killapp
  - com.networknt.chaos.LatencyAssaultHandler@latency
  - com.networknt.chaos.MemoryAssaultHandler@memory
  - com.networknt.chaos.ExceptionAssaultHandler@exchaos
  - com.networknt.chaos.ChaosMonkeyGetHandler@chaosget
  - com.networknt.chaos.ChaosMonkeyPostHandler@chaospost
  - com.networknt.health.HealthGetHandler@health
  - com.networknt.info.ServerInfoGetHandler@info
  - com.networknt.logging.handler.LoggerGetHandler@getLogger
  - com.networknt.logging.handler.LoggerPostHandler@postLogger
  - com.networknt.logging.handler.LoggerGetLogContentsHandler@getLogContents
  - com.networknt.config.reload.handler.ModuleRegistryGetHandler@modules
  - com.networknt.config.reload.handler.ConfigReloadHandler@configReload
  - com.networknt.specification.SpecDisplayHandler@spec
  - com.networknt.specification.SpecSwaggerUIHandler@swaggerui
  - com.networknt.specification.FaviconHandler@favicon
  - com.networknt.router.OAuthServerHandler@oauth
  - com.networknt.router.OAuthServerGetHandler@getOauth
  - com.networknt.server.handler.ServerShutdownHandler@shutdown

handler.chains.default:
  - exception
  - metrics
  - traceability
  - correlation
  - killapp
  - latency
  - memory
  - exchaos
  - cors
  # - stateless
  - header
  - specification
  - security
  - body
  - audit
  - sanitizer
  - validator
  # - prefix
  - router
  - proxy

# cache.yml
cache.caches:
  - cacheName: jwt
    expiryInMinutes: 15
    maxSize: 100
  - cacheName: jwk
    expiryInMinutes: 129600
    maxSize: 100
