header2path-transformer:        
  ruleId: header2path-transformer
  host: sunlife                    
  ruleType: header2path-transform
  visibility: public                    
  description: Transform the header parameter to path parameter
  conditions:
    - conditionId: dynPathHeader
      propertyPath: header    
      operatorCode: EQ             
      joinCode: OR
      index: 1
      conditionValues:             
        - conditionValueId: header
          conditionValue: /gateway/ICAS_Mortgages_SPO/1.0
          # conditionValue: /sites/Operations
  actions:
    - actionId: header2path-transform
      actionClassName: ca.sunlife.eadp.path.HeaderPathTransformAction
      actionValues:
        - actionValueId: direction
          value: request