hosts:
  - domain: local.lightapi.net
    path: /
    #base: /home/steve/light-chain/light-config-test/light-router/local-direct/lightapi/build
    base: /lightapi/build
    transferMinSize: 10245760
    directoryListingEnabled: false
  - domain: devsignin.lightapi.net
    path: /
    #base: /home/steve/light-chain/light-config-test/light-router/local-direct/signin/build
    base: /signin/build
    transferMinSize: 10245760
    directoryListingEnabled: false
