# local rules

conquest-token-request:
  ruleId: conquest-token-request
  host: lightapi.net
  ruleType: request-transform
  visibility: public
  description: Add the conquest token to the request
  conditions:
    - conditionId: path-conquest
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /conquest
  actions:
    - actionId: conquest-request-transform
      actionClassName: com.networknt.rule.conquest.ConquestTokenRequestTransformAction

context-validator-request:
  ruleId: context-validator-request
  host: lightapi.net
  ruleType: request-transform
  visibility: public
  description: Context validator
  conditions:
    - conditionId: path-conquest
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /context
  actions:
    - actionId: context-request-transform
      actionClassName: com.networknt.rule.validator.ContextValidatorRequestTransformAction

epam-token-request:
  ruleId: epam-token-request
  host: lightapi.net
  ruleType: request-transform
  visibility: public
  description: Get EPAM token
  conditions:
    - conditionId: path-conquest
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /epam
  actions:
    - actionId: epam-request-transform
      actionClassName: com.networknt.rule.epam.EpamTokenRequestTransformAction

xml-json-request:
  ruleId: xml-json-request
  host: lightapi.net
  ruleType: request-transform
  visibility: public
  description: Get EPAM token
  conditions:
    - conditionId: path-conquest
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /xmltojson
  actions:
    - actionId: xml-json-request-transform
      actionClassName: com.networknt.rule.soap.Rest2SoapTransformAction

json-xml-request:
  ruleId: json-xml-request
  host: lightapi.net
  ruleType: request-transform
  visibility: public
  description: Get EPAM token
  conditions:
    - conditionId: path-conquest
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /xmltojson
  actions:
    - actionId: json-xml-request-transform
      actionClassName: com.networknt.rule.soap.Soap2RestTransformAction

soap-security-request:
  ruleId: soap-security-request
  host: lightapi.net
  ruleType: request-transform
  visibility: public
  description: Transform the request body to add the security section into the header for soap API call for external service.
  conditions:
    - conditionId: path-soap
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /devext/CANX/AntcMultiService
  actions:
    - actionId: soap-request-transform
      actionClassName: com.networknt.soap.SoapSecurityTransformAction

snow-security-request:
  ruleId: snow-security-request
  host: lightapi.net
  ruleType: request-transform
  visibility: public
  description: Transform the request body to add the security section into the header for soap API call for external service.
  conditions:
    - conditionId: path-soap
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /devext/CANX/AntcMultiService
  actions:
    - actionId: soap-request-transform
      actionClassName: com.networknt.rule.snow.SnowTokenRequestTransformAction

tealium-security-request:
  ruleId: tealium-security-request
  host: lightapi.net
  ruleType: request-transform
  visibility: public
  description: Transform the request body to add the security section into the header for soap API call for external service.
  conditions:
    - conditionId: path-soap
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /devext/CANX/AntcMultiService
  actions:
    - actionId: soap-request-transform
      actionClassName: com.networknt.rule.tealium.TealiumTokenRequestTransformAction

petstore-request-header-replace:
  ruleId: petstore-request-header-replace
  host: lightapi.net
  ruleType: request-transform
  visibility: public
  description: Transform the request to replace one header with the other header.
  conditions:
    - conditionId: path-pets
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /v1/pets
  actions:
    - actionId: header-transform
      actionClassName: com.networknt.rule.header.HeaderReplaceRequestTransformAction
      actionValues:
        - actionValueId: sourceHeader
          value: Flink-Token
        - actionValueId: targetHeader
          value: Authorization
        - actionValueId: removeSourceHeader
          value: true
petstore-response-header-replace:
  ruleId: petstore-response-header-replace
  host: lightapi.net
  ruleType: response-transform
  visibility: public
  description: Transform the response to replace one header with the other header.
  conditions:
    - conditionId: path-pets
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /v1/pets
  actions:
    - actionId: header-transform
      actionClassName: com.networknt.rule.header.HeaderReplaceResponseTransformAction
      actionValues:
        - actionValueId: sourceHeader
          value: X-Test-1
        - actionValueId: targetHeader
          value: My-Header

body-sanitizer-request:
  ruleId: body-sanitizer-request
  host: lightapi.net
  ruleType: request-transform
  visibility: public
  description: Transform the request body based on the sanitizer.yml to encode the request body for cross-site scripting.
  conditions:
    - conditionId: path-sanitizer
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /v1/pets
  actions:
    - actionId: sanitizer-request-transform
      actionClassName: com.networknt.rule.sanitizer.BodySanitizerTransformAction
