# local rules

petstore-notifications-transformer:
  ruleId: petstore-notifications-transformer
  host: lightapi.net
  ruleType: response-transform
  visibility: public
  description: Transform the response body from a complicated structure to a simple one in the light-gateway or http-sidecar.
  conditions:
    - conditionId: path-notifications
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /v1/notifications
  actions:
    - actionId: notification-transform
      actionClassName: com.networknt.notification.NotificationTransformAction

petstore-request-path:
  ruleId: petstore-request-path
  host: lightapi.net
  ruleType: request-transform
  visibility: public
  description: Transform the request path based on the context header as the prefix.
  conditions:
    - conditionId: path-pets
      propertyPath: requestPath
      operatorCode: EQ
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /pets
  actions:
    - actionId: path-transform
      actionClassName: com.networknt.path.HeaderPathTransformAction
