xml2json-transformer:              
  ruleId: xml2json-transformer
  host: sunlife                    
  ruleType: request-transform     
  visibility: public                    
  description: Transform the response body from XML to JSON
  conditions:
    - conditionId: path-notifications
      propertyPath: requestPath    
      operatorCode: EQ             
      joinCode: AND
      index: 1
      conditionValues:             
        - conditionValueId: path
          conditionValue: /aizws/MrasLabProxy/1.0   
  actions:
    - actionId: xml2json-transform
      actionClassName: ca.sunlife.eadp.Xml2JsonTransformAction   
      actionValues:
        - actionValueId: direction
          value: request

json2xml-transformer:              
  ruleId: json2xml-transformer
  host: sunlife                    
  ruleType: response-transform     
  visibility: public                    
  description: Transform the response body from JSON to XML
  conditions:
    - conditionId: path-notifications
      propertyPath: requestPath    
      operatorCode: EQ             
      joinCode: AND
      index: 1
      conditionValues:             
        - conditionValueId: path
          conditionValue: /aizws/MrasLabProxy/1.0   
  actions:
    - actionId: xml2json-transform
      actionClassName: ca.sunlife.eadp.Json2XmlTransformAction   
      actionValues:
        - actionValueId: direction
          value: response

soap-security-request:
  ruleId: soap-security-request
  host: https://wwwdev.cannex.com
  ruleType: request-transform
  visibility: public
  description: Transform the request body to add security to soap request
  conditions:
    - conditionId: path-soap
      propertyPath: requestPath
      operatorCode: EQ             
      joinCode: AND
      index: 1
      conditionValues:             
        - conditionValueId: path
          conditionValue: /devext/CANX/AntcMultiService
  actions:
    - actionId: soap-request-transform
      actionClassName: ca.sunlife.eadp.cannex.SoapSecurityTransformAction  
      actionValues:
        - actionValueId: username
          value: SLUATWS
        - actionValueId: password
          value: J3PGDSEHSTRIT1FJYHPW
                       
flinks-request-header-replace:
  ruleId: flinks-request-header-replace
  host: https://sunlifedev-api.private.fin.ag
  ruleType: request-transform
  visibility: public
  description: Transform the request to replace one header with the other header.
  conditions:
    - conditionId: BankingServices
      propertyPath: requestPath
      operatorCode: MATCH
      joinCode: AND
      index: 1
      conditionValues:
        - conditionValueId: path
          conditionValue: /v3/(.*)/BankingServices/(.*)
    - conditionId: insight
      propertyPath: requestPath
      operatorCode: MATCH
      joinCode: OR
      index: 2
      conditionValues:
        - conditionValueId: path
          conditionValue: /v3/(.*)/insight/login/(.*)/attributes/(.*)
    - conditionId: Investments
      propertyPath: requestPath
      operatorCode: MATCH
      joinCode: OR
      index: 3
      conditionValues:
        - conditionValueId: path
          conditionValue: /v3/(.*)/Investments
    - conditionId: attributes
      propertyPath: requestPath
      operatorCode: MATCH
      joinCode: OR
      index: 4
      conditionValues:
        - conditionValueId: path
          conditionValue: /v3/(.*)/attributes/(.*)

  actions:
    - actionId: header-transform
      actionClassName: com.networknt.rule.HeaderReplaceRequestTransformAction   
      actionValues:
        - actionValueId: sourceHeader
          value: flinks-token
        - actionValueId: targetHeader
          value: Authorization
        - actionValueId: removeSourceHeader
          value: true
